### PR TITLE
[157] Spiller serialization optimizations

### LINKED ISSUE #157: Performance Improvement in Spilling to Disk
### Software Environment:
- OpenLooKeng version (source or binary):1.4.0

- OS platform & distribution (eg., Linux Ubuntu 16.04):Linux

- Java version:1.8
### Describe the current behavior

More time consumption in writing to files and reading from files when spilling is enabled.   

### Describe the expected behavior
Improvement in writing and reading of files from disk when spilling is enabled.

### Steps to reproduce the issue
1.
2.
3.

### Special notes for this issue

### PR DESCRIPTION
**Pull request by Nitin-Kashyap**
### What type of PR is this?
/kind feature

### What does this PR do / why do we need it:
* Single pass direct serialize / deserialize, instead of 2 pass (Page -> SerializedPage -> file/stream)
* Added Snappy Compressed writter
* Added configuration for direct serializer enable
* Added Spill/Unspill Timing stats capture and relayed to CLI

Performance test observation: [over TPCDS Q74]
|Sl No | Base(No Spill) | Base(With Spill) | with Direct  | Improvement  |
|---|---|---|---|---|
| Spill Write (s)  |  0 | 999.2  | 684  |  31.5% |
| Spill Read (s) |  0 |  256 |   151|   41.0%|
| Overall Spill (m) |  0 |  4.21 |  2.77 |  33.5% |
| QueryTime (m) |  5.89 |  25.58 |  20.19 |  19.6% |
| QueryTime Degrade(Ratio) |  0 |  4.3x |  3.3x |  1x |

### Which issue(s) this PR fixes:

Fixes #157 , #I4JUF0

### Special notes for your reviewers:

### CODE REVIEW

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/GenericPagesSerde.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    default SerializedPage serialize(Page page)
+    {
+        throw new PrestoException(StandardErrorCode.NOT_FOUND, "Implementations for step serialization not found");
+    }
+
+    default Page deserialize(SerializedPage page)
+    {
+        throw new PrestoException(StandardErrorCode.NOT_FOUND, "Implementations for step deserialization not found");
+    }
+
```
Comment (Nitin-Kashyap) [inline hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/GenericPagesSerde.java:35]: Add comment for 2 additional interfaces

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeFactory.java [hunk 2]
```diff
@@ -26,25 +26,36 @@
 {
     private final BlockEncodingSerde blockEncodingSerde;
     private final boolean compressionEnabled;
+    private final boolean directSerDe;
```
Comment (Nitin-Kashyap) [inline hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeFactory.java:29]: rename directSerDe to useStreamingSerde

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/SliceStreamPageSerde.java [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+    }
+
+    @Override
+    public Page deserialize(InputStream input)
+    {
+        checkArgument(input instanceof SliceInput, "Page serializer does not support (" + input.getClass().getSimpleName() + ") for reading");
+        return readPage((SliceInput) input);
+    }
+
+    private void writePage(SliceOutput output, Page page)
```
Comment (Nitin-Kashyap) [inline hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/SliceStreamPageSerde.java:62]: Check if can use pagesSerdeUtils writePage routines for this

File: presto-main/src/main/java/io/prestosql/metadata/InternalBlockEncodingSerde.java [hunk 4]
```diff
@@ -74,7 +74,7 @@ public void writeBlock(SliceOutput output, Block block)
         }
     }
 
-    private static String readLengthPrefixedString(SliceInput input)
+    protected static String readLengthPrefixedString(SliceInput input)
```
Comment (Nitin-Kashyap) [inline presto-main/src/main/java/io/prestosql/metadata/InternalBlockEncodingSerde.java:77]: not required

File: presto-main/src/main/java/io/prestosql/spiller/FileSingleStreamSpillerFactory.java [hunk 5]
```diff
@@ -148,14 +154,14 @@ private static void cleanupOldSpillFiles(Path path)
     }
 
     @Override
-    public SingleStreamSpiller create(List<Type> types, SpillContext spillContext, LocalMemoryContext memoryContext)
+    public SingleStreamSpiller create(List<Type> types, SpillContext spillContext, LocalMemoryContext memoryContext, boolean useDirect)
```
Comment (Nitin-Kashyap) [inline presto-main/src/main/java/io/prestosql/spiller/FileSingleStreamSpillerFactory.java:157]: Remove useDirect parameter

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/GenericPagesSerde.java (hunk 1 above)
Comment (Nitin-Kashyap) [reply hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/GenericPagesSerde.java:35]: fixed

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeFactory.java (hunk 2 above)
Comment (Nitin-Kashyap) [reply hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeFactory.java:29]: fixed

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/SliceStreamPageSerde.java (hunk 3 above)
Comment (Nitin-Kashyap) [reply hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/SliceStreamPageSerde.java:62]: not duplicate

File: presto-main/src/main/java/io/prestosql/metadata/InternalBlockEncodingSerde.java (hunk 4 above)
Comment (Nitin-Kashyap) [reply presto-main/src/main/java/io/prestosql/metadata/InternalBlockEncodingSerde.java:77]: Fixed

File: presto-main/src/main/java/io/prestosql/spiller/FileSingleStreamSpillerFactory.java (hunk 5 above)
Comment (Nitin-Kashyap) [reply presto-main/src/main/java/io/prestosql/spiller/FileSingleStreamSpillerFactory.java:157]: Fixed
