### PR TITLE
spotbug fix for TestBTreeIndex

### LINKED ISSUE #193: spotbug fix for TestBTreeIndex
### Software Environment:
- OpenLooKeng version (source or binary): latest master

- OS platform & distribution (eg., Linux Ubuntu 16.04): any

- Java version: NA
### Steps to reproduce the issue
1.
2.
3.

### Special notes for this issue

### PR DESCRIPTION
**Pull request by Rakshithreddya**
### What type of PR is this?

/kind bug

### What does this PR do / why do we need it:
spotbug fix for TestBTreeIndex
### Which issue(s) this PR fixes:

Fixes #193 

### Special notes for your reviewers:

### CODE REVIEW

File: hetu-heuristic-index/src/test/java/io/hetu/core/plugin/heuristicindex/index/btree/TestBTreeIndex.java [hunk 1]
```diff
@@ -306,7 +307,10 @@ public void testSerialize()
         }
         File file = File.createTempFile("test-serialize-", UUID.randomUUID().toString());
         index.serialize(new FileOutputStream(file));
-        file.delete();
+        boolean ret=file.delete();
+        if(!ret){
```
Comment (sraghunandan) [inline hetu-heuristic-index/src/test/java/io/hetu/core/plugin/heuristicindex/index/btree/TestBTreeIndex.java:311]: This will fail with checkstyle error

Comment (Rakshithreddya) [reply hetu-heuristic-index/src/test/java/io/hetu/core/plugin/heuristicindex/index/btree/TestBTreeIndex.java]: fixed
