### PR TITLE
Spill Prefetch Read and Prioritizing Larger splits in Memory Revoke

### LINKED ISSUE #157: Performance Improvement in Spilling to Disk
### Software Environment:
- OpenLooKeng version (source or binary):1.4.0

- OS platform & distribution (eg., Linux Ubuntu 16.04):Linux

- Java version:1.8
### Describe the current behavior

More time consumption in writing to files and reading from files when spilling is enabled.   

### Describe the expected behavior
Improvement in writing and reading of files from disk when spilling is enabled.

### Steps to reproduce the issue
1.
2.
3.

### Special notes for this issue

### PR DESCRIPTION
**Pull request by sumanth43**
### What type of PR is this?

kind task 

### Which issue(s) this PR fixes:

Fixes #157 #I4JUF0

### Special notes for your reviewers:

Query: select * from web_sales  order by ws_sold_time_sk;
Readings were taken with Single spiller thread(experimental.spiller-threads=1)

Readings with Base Code:

Spill Writing time = 2125.60995 ms
Spill reading time = 809.68725 ms

Readings with Modifications:

Spill Writing time = 1709.20986 ms
Spill reading time= 389.438095 ms

### CODE REVIEW

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java [hunk 1]
```diff
@@ -155,21 +165,38 @@ public static long writePages(PagesSerde serde, SliceOutput sliceOutput, Iterato
     {
         private final PagesSerde serde;
         private final SliceInput input;
+        private final int prefetchSize;
+        List<Page> prefetchedPages;
 
         PageReader(PagesSerde serde, SliceInput input)
+        {
+            this(serde, input, 1);
```
Comment (Nitin-Kashyap) [inline hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java:173]: intead of 1 define constant as NO_PREFETCH=1 and use that

File: presto-main/src/main/java/io/prestosql/execution/MemoryRevokingScheduler.java [hunk 2]
```diff
@@ -73,7 +79,9 @@ public MemoryRevokingScheduler(
                 requireNonNull(sqlTaskManager, "sqlTaskManager cannot be null")::getAllTasks,
                 requireNonNull(taskManagementExecutor, "taskManagementExecutor cannot be null").getExecutor(),
                 config.getMemoryRevokingThreshold(),
-                config.getMemoryRevokingTarget());
+                config.getMemoryRevokingTarget(),
+                config.isPrioritizeLargerSpiltsMemoryRevoke(),
+                config.getRevocableMemoryLimit());
```
Comment (Nitin-Kashyap) [inline presto-main/src/main/java/io/prestosql/execution/MemoryRevokingScheduler.java:84]: this name is not correct; should be something like revokable memory selection threshold

File: presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java [hunk 3]
```diff
@@ -1401,4 +1404,40 @@ public FeaturesConfig setSkipNonApplicableRulesEnabled(boolean skipNonApplicable
...
+        this.revocableMemoryLimit = revocableMemoryLimit;
+        return this;
+    }
+
+    public int getSpillPrefetchReadSize()
+    {
+        return spillPrefetchReadSize;
+    }
+
+    @Config("experimental.spill-prefetch-read-size")
```
Comment (Nitin-Kashyap) [inline presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java:1437]: should be read-pages and not read-size...

File: presto-main/src/main/java/io/prestosql/execution/MemoryRevokingScheduler.java [hunk 4]
```diff
@@ -244,34 +256,105 @@ public Long mergeResults(List<Long> childrenResults)
...
-                .filter(task -> task.getQueryContext().getMemoryPool() == memoryPool)
-                .sorted(ORDER_BY_CREATE_TIME)
-                .forEach(task -> task.getQueryContext().accept(new VoidTraversingQueryContextVisitor<AtomicLong>()
-                {
-                    @Override
-                    public Void visitQueryContext(QueryContext queryContext, AtomicLong remainingBytesToRevoke)
+        Map<Long, List<SqlTask>> revocableMemoryMapping = new HashMap<>();
+
+        if (prioritizeLargerSpiltsMemoryRevoke) {
+            sqlTasks.stream()
```
Comment (Nitin-Kashyap) [inline presto-main/src/main/java/io/prestosql/execution/MemoryRevokingScheduler.java:262]: Mention in comment this approach disregards create time.

**Review by Nitin-Kashyap — CHANGES_REQUESTED** [review]

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java (hunk 1 above)
Comment (sumanth43) [reply hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java]: addressed

File: presto-main/src/main/java/io/prestosql/execution/MemoryRevokingScheduler.java (hunk 2 above)
Comment (sumanth43) [reply presto-main/src/main/java/io/prestosql/execution/MemoryRevokingScheduler.java]: fixed

File: presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java (hunk 3 above)
Comment (sumanth43) [reply presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java]: fixed

File: presto-main/src/main/java/io/prestosql/execution/MemoryRevokingScheduler.java (hunk 4 above)
Comment (sumanth43) [reply presto-main/src/main/java/io/prestosql/execution/MemoryRevokingScheduler.java:263]: addressed

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java [hunk 5]
```diff
@@ -186,22 +210,38 @@ protected Page computeNext()
...
+            this(serde, input, eof, NO_PREFETCH);
+        }
+
+        PageReaderDirect(GenericPagesSerde serde, InputStream input, Predicate<InputStream> eof, int spillPrefetchReadPages)
         {
             this.serde = requireNonNull(serde, "serde is null");
             this.input = requireNonNull(input, "input is null");
             this.eof = requireNonNull(eof, "End of data needs to passed");
+            if (spillPrefetchReadPages > 0) {
+                this.prefetchedPages = new ArrayList<>(spillPrefetchReadPages);
```
Comment (Nitin-Kashyap) [inline hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java:227]: Use LinkedList instead of ArrayList.. 

and for remove, use removeFirst

File: presto-cli/src/main/java/io/prestosql/cli/StatusPrinter.java [hunk 6]
```diff
@@ -208,9 +208,9 @@ public void printFinalInfo()
 
             // Spilled Data: 20GB, Writing Time: 22s, Reading Time: 1.2s
             if (stats.getSpilledBytes() > 0) {
-                Duration readTime = millis(stats.getElapsedSpillReadTimeMillis());
-                Duration writeTime = millis(stats.getElapsedSpillWriteTimeMillis());
-                String summary = String.format("Spilled: %s, Writing Time: %.1fs, Reading Time: %.1fs",
+                Duration readTime = millis(stats.getElapsedSpillReadTimeMillis() / nodes);
```
Comment (Nitin-Kashyap) [inline presto-cli/src/main/java/io/prestosql/cli/StatusPrinter.java:211]: what if all nodes don't flush? use the count of the nodes that did

File: presto-main/src/main/java/io/prestosql/event/QueryMonitor.java [hunk 7]
```diff
@@ -454,6 +456,9 @@ private static void logQueryTimeline(QueryInfo queryInfo)
             long executionInitializationTime = max(firstTaskStartTime - firstStageFirstTaskStartTime, 0);
             long running = max(lastTaskEndTime - firstTaskStartTime, 0);
             long finishing = max(queryEndTime.getMillis() - lastTaskEndTime, 0);
+            int nodes = globalUniqueNodes(outputStage).size();
+            long spilledWriteTimeMillisPerNode = (queryStats.getSpilledWriteTime().toMillis() / nodes);
```
Comment (Nitin-Kashyap) [inline presto-main/src/main/java/io/prestosql/event/QueryMonitor.java:460]: should nodes include the nodes where spill occurred?

File: presto-main/src/test/java/io/prestosql/spiller/TestFileSingleStreamSpiller.java [hunk 8]
```diff
@@ -289,46 +289,46 @@ private Page buildPageBenchmark()
...
-        assertSpillBenchmarkReadingUsingWorkProcessor(false, true, "1GB", 1, false);
-        assertSpillBenchmarkReadingUsingWorkProcessor(false, true, "1GB", 1, true);
+        assertSpillBenchmarkReadingUsingWorkProcessor(false, true, "1GB", 1, false, 1);
+        assertSpillBenchmarkReadingUsingWorkProcessor(false, true, "1GB", 1, true, 1);
 
-        assertSpillBenchmarkReadingUsingWorkProcessor(true, true, "1GB", 1, false);
-        assertSpillBenchmarkReadingUsingWorkProcessor(true, true, "1GB", 1, true);
+        assertSpillBenchmarkReadingUsingWorkProcessor(true, true, "1GB", 1, false, 1);
+        assertSpillBenchmarkReadingUsingWorkProcessor(true, true, "1GB", 1, true, 1);
     }
```
Comment (Nitin-Kashyap) [inline presto-main/src/test/java/io/prestosql/spiller/TestFileSingleStreamSpiller.java:329]: Add test case with higher prefetch size also

File: presto-main/src/main/java/io/prestosql/server/protocol/Query.java [hunk 9]
```diff
@@ -874,7 +874,7 @@ private static StageStats toStageStats(StageInfo stageInfo)
                 .build();
     }
 
-    private static Set<String> globalUniqueNodes(StageInfo stageInfo)
+    public static Set<String> globalUniqueNodes(StageInfo stageInfo)
```
Comment (Nitin-Kashyap) [inline presto-main/src/main/java/io/prestosql/server/protocol/Query.java:877]: May be need to get only those where the stage has non-zero spill stats

File: hetu-docs/en/admin/properties.md [hunk 10]
```diff
@@ -240,6 +240,34 @@ This section describes the most important config properties that may be used to
...
+> Sets number of pages prefetched while reading from spilled files.
+
+### `experimental.revocable-memory-selection-threshold`
+
+> -   **Type:** `data size`
+> -   **Default value:** `512 MB`
+>
+> Sets memory selection threshold for revocable memory of operator to directly allocate revocable memory for remaining bytes ready to revoke. 
+
+### `experimental.prioritize-larger-spilts-memory-revoke`
```
Comment (sraghunandan) [inline hetu-docs/en/admin/properties.md:264]: keep this true by default

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java (hunk 5 above)
Comment (sumanth43) [reply hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java]: Fixed

File: presto-cli/src/main/java/io/prestosql/cli/StatusPrinter.java (hunk 6 above)
Comment (sumanth43) [reply presto-cli/src/main/java/io/prestosql/cli/StatusPrinter.java]: Fixed

File: presto-main/src/main/java/io/prestosql/event/QueryMonitor.java (hunk 7 above)
Comment (sumanth43) [reply presto-main/src/main/java/io/prestosql/event/QueryMonitor.java]: Fixed

File: presto-main/src/test/java/io/prestosql/spiller/TestFileSingleStreamSpiller.java (hunk 8 above)
Comment (sumanth43) [reply presto-main/src/test/java/io/prestosql/spiller/TestFileSingleStreamSpiller.java:347]: Added

File: presto-main/src/main/java/io/prestosql/server/protocol/Query.java (hunk 9 above)
Comment (sumanth43) [reply presto-main/src/main/java/io/prestosql/server/protocol/Query.java]: Fixed

File: hetu-docs/en/admin/properties.md (hunk 10 above)
Comment (sumanth43) [reply hetu-docs/en/admin/properties.md:264]: Modified

File: presto-main/src/main/java/io/prestosql/spiller/NodeSpillConfig.java [hunk 11]
```diff
@@ -89,4 +91,16 @@ public NodeSpillConfig setSpillDirectSerdeEnabled(boolean spillDirectSerdeEnable
         this.spillDirectSerdeEnabled = spillDirectSerdeEnabled;
         return this;
     }
+
+    public int getSpillPrefetchReadPages()
+    {
+        return spillPrefetchReadPages;
+    }
+
+    @Config("experimental.spill-prefetch-read-pages")
```
Comment (sraghunandan) [inline presto-main/src/main/java/io/prestosql/spiller/NodeSpillConfig.java:100]: Dont we need to have a Max config? else the configuration can be made to peform DOS attack

Comment (sumanth43) [reply presto-main/src/main/java/io/prestosql/spiller/NodeSpillConfig.java:104]: Added Max config

File: presto-main/src/main/java/io/prestosql/event/QueryMonitor.java [hunk 12]
```diff
@@ -522,9 +529,11 @@ private static void logQueryTimeline(
             long runningMillis,
             long finishingMillis,
             DateTime queryStartTime,
-            DateTime queryEndTime)
+            DateTime queryEndTime,
+            long spilledWriteTimeMillisPerNode,
+            long spilledReadTimeMillisPerNode)
     {
-        log.info("TIMELINE: Query %s :: Transaction:[%s] :: elapsed %sms :: syntaxAnalysisTime %sms :: planning %sms :: logicalPlanningMillis %sms :: physicalPlanningMillis %sms :: distributionPlanTime %sms :: waiting %sms :: scheduling %sms :: executionInitializationTime %sms :: running %sms :: finishing %sms :: begin %s :: end %s",
+        log.info("TIMELINE: Query %s :: Transaction:[%s] :: elapsed %sms :: syntaxAnalysisTime %sms :: planning %sms :: logicalPlanningMillis %sms :: physicalPlanningMillis %sms :: distributionPlanTime %sms :: waiting %sms :: scheduling %sms :: executionInitializationTime %sms :: running %sms :: finishing %sms :: begin %s :: end %s :: spilledWriteTimeMillisPerNode %sms :: spilledReadTimeMillisPerNode %sms",
```
[the remark this answers is not in the document]
Comment (sumanth43) [reply presto-main/src/main/java/io/prestosql/event/QueryMonitor.java]: Corrected Order

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java [hunk 13]
```diff
@@ -147,36 +151,56 @@ public static long writePages(PagesSerde serde, SliceOutput sliceOutput, Iterato
...
         PageReader(GenericPagesSerde serde, SliceInput input)
+        {
+            this(serde, input, NO_PREFETCH);
+        }
+
+        PageReader(GenericPagesSerde serde, SliceInput input, int spillPrefetchReadPages)
         {
             this.serde = requireNonNull(serde, "serde is null");
             this.input = requireNonNull(input, "input is null");
+            if (spillPrefetchReadPages > 0) {
```
[the remark this answers is not in the document]
Comment (sumanth43) [reply hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java]: added checkArgument

File: hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java [hunk 14]
```diff
@@ -38,6 +40,8 @@
 
 public class PagesSerdeUtil
 {
+    public static final int NO_PREFETCH = 1;
```
[the remark this answers is not in the document]
Comment (sumanth43) [reply hetu-transport/src/main/java/io/hetu/core/transport/execution/buffer/PagesSerdeUtil.java]: Addressed
