### PR TITLE
OpenStream and return value ignored fixed

### LINKED ISSUE #241: OpenStream and return value ignored issue in MemoryTableManager
### Software Environment:
- OpenLooKeng version (source or binary):

- OS platform & distribution (eg., Linux Ubuntu 16.04):

- Java version:
### Describe the current behavior
OpenStream and return value ignored issue

### Steps to reproduce the issue
1.
2.
3.

### Special notes for this issue

### PR DESCRIPTION
**Pull request by rishabhmurarka7**
### What type of PR is this?

Uncomment only one /kind <> line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug
### Which issue(s) this PR fixes: 

Fixes #241 

### Special notes for your reviewers:

### CODE REVIEW

File: presto-memory/src/main/java/io/prestosql/plugin/memory/data/MemoryTableManager.java [hunk 1]
```diff
@@ -404,15 +405,21 @@ private synchronized void spillTable(long id)
         if (!Files.exists(tablePath)) {
             Files.createDirectories(tablePath);
         }
+        ObjectOutputStream oos = null;
         table.setState(Table.TableState.SPILLED);
         try (OutputStream outputStream = Files.newOutputStream(tablePath.resolve(TABLE_METADATA_SUFFIX))) {
-            ObjectOutputStream oos = new ObjectOutputStream(outputStream);
+            oos = new ObjectOutputStream(outputStream);
```
Comment (Nitin-Kashyap) [inline presto-memory/src/main/java/io/prestosql/plugin/memory/data/MemoryTableManager.java:411]: it can be written in try () statment itself.

```java
try (OutputStream outputStream = new ObjectOutputStream(Files.newOutputStream(tablePath.resolve(TABLE_METADATA_SUFFIX)))) {
   ...
}
```

File: presto-memory/src/main/java/io/prestosql/plugin/memory/data/MemoryTableManager.java [hunk 2]
```diff
@@ -437,13 +444,19 @@ public synchronized void restoreTable(long id)
         if (!Files.exists(tablePath)) {
             throw new FileNotFoundException("No spill data found for table id " + id);
         }
+        SecureObjectInputStream ois = null;
         try (InputStream inputStream = Files.newInputStream(tablePath.resolve(TABLE_METADATA_SUFFIX))) {
-            SecureObjectInputStream ois = new SecureObjectInputStream(inputStream, Table.TYPES_WHITELIST);
+            ois = new SecureObjectInputStream(inputStream, Table.TYPES_WHITELIST);
```
Comment (Nitin-Kashyap) [inline presto-memory/src/main/java/io/prestosql/plugin/memory/data/MemoryTableManager.java:449]: Can write in the try statement itself

File: presto-memory/pom.xml [hunk 3]
```diff
@@ -220,5 +220,9 @@
             <artifactId>testing-mysql-server</artifactId>
             <scope>test</scope>
         </dependency>
+        <dependency>
+            <groupId>org.testng</groupId>
+            <artifactId>testng</artifactId>
```
Comment (Nitin-Kashyap) [inline presto-memory/pom.xml:225]: Scope should be test... need not include for final bin

File: presto-memory/src/main/java/io/prestosql/plugin/memory/data/MemoryTableManager.java [hunk 4]
```diff
@@ -476,7 +475,7 @@ private synchronized void applyForMemory(long bytes, long reserved, Runnable onS
         long newSize = bytes + currentBytes.get();
         while (maxBytes < newSize) {
             logNumFormat("Not enough memory for the request. Current bytes: %s. Limit: %s. Requested size: %s", currentBytes.get(), maxBytes, bytes);
-            tables.get(reserved); // perform a get and make sure reserved table is not LRU
+            assertNotNull(tables.get(reserved)); // perform a get and make sure reserved table is not LRU
```
Comment (Nitin-Kashyap) [inline presto-memory/src/main/java/io/prestosql/plugin/memory/data/MemoryTableManager.java:478]: Why assert here.. if unexpected better use checkArgument() or requiredNotNull()

**Comment by Nitin-Kashyap** [comment]
Lgtm
