### PR TITLE
[I4NBP3] [260] Single Column Read or Update Issue Fix

### LINKED ISSUE #260: An error occurs when data is updated without the where condition.
### Software Environment:
- OpenLooKeng version (source or binary): openLooKeng1.5.0RC3（2021-12-18）

- OS platform & distribution (eg., Linux Ubuntu 16.04):

- Java version:
### Describe the current behavior

in step 4:Failed to update data without the where condition

### Describe the expected behavior

in step 4:Succeeded in updating data without the where condition.

### Steps to reproduce the issue
1.1.create table on olk:
CREATE TABLE testorders02(orderkey array(varchar), orderstatus row(big int), lables map(varchar, integer)) WITH (format='orc',transactional=true);
2.insert data:
INSERT INTO testorders02 VALUES (ARRAY ['YOUNG', 'FASION', 'STYLE'], row(111), MAP(ARRAY ['type', 'grand'], ARRAY [1, 2]));
3.query data:
select * from testorders02;
4.update table without where:
update testorders02 set orderkey=ARRAY['UPDATE','UPDATE','UPDATE'];

### Special notes for this issue

### PR DESCRIPTION
**Pull request by sumanth43**
### What type of PR is this?

Uncomment only one /kind <> line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug 

### Which issue(s) this PR fixes:

Fixes #260 #I4NBP3

### Special notes for your reviewers:

### CODE REVIEW

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java [hunk 1]
```diff
@@ -6888,4 +6888,30 @@ public void testAlterTableWithStructDataTypeColumns()
...
+        assertEquals(computeActual("SELECT * FROM testReadSchema2.testReadStruct7").getRowCount(), 1);
+        assertUpdate("DROP TABLE testReadSchema2.testReadStruct7");
+        assertUpdate("DROP SCHEMA testReadSchema2");
+    }
+
+    @Test
+    public void testReadSingleColumnStructDataTypeColumns()
+    {
+        assertUpdate("CREATE SCHEMA testReadSchema3");
+        assertUpdate("CREATE TABLE testReadSchema3.testReadStruct8 (orderkey array(varchar), orderstatus array(row(big int)), lables map(varchar, array(int)), orderstatus1 row(big2 int))  WITH (format='orc',transactional=true)");
```
Comment (Nitin-Kashyap) [inline presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java:6909]: add test case with native types and complex types alternating types.
add queries for : -
a) each Col name separately
b) combinations of colms with difference of 2 or more colindex,

File: presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java [hunk 2]
```diff
@@ -621,15 +623,14 @@ private static void verifyAcidColumn(OrcReader orcReader, int columnIndex, Strin
         List<Integer> desiredColumnsIndex = desiredColumnsByNumber.keySet().stream().collect(Collectors.toList());
         Map<Integer, OrcColumn> fileColumnsByNumber = fileColumns.stream()
                 .collect(toImmutableMap(orcColumn -> orcColumn.getColumnId().getId(), identity()));
-
-        int skipStructColumnCount = 0;
-        HiveColumnHandle handle = null;
-        OrcColumn column = null;
+        for (OrcColumn orcColumn : fileColumns) {
```
Comment (Nitin-Kashyap) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java:626]: Why do 2 passes on fileColumns? it can be merged into single pass itself.

Comment (sumanth43) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java:621]: Made into single pass

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java (hunk 1 above)
Comment (sumanth43) [reply presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java:6909]: added test case

**Comment by Nitin-Kashyap** [comment]
lgtm
